import { env, inNiaDemoMode as inDemoMode } from '@/lib/env';
import snapshotsRaw from '@/lib/nia/snapshots.json';

// Pre-captured real responses from Nia for canonical demo queries. These let
// the demo run even when:
//   - Nia rate-limits the account (the daily 1M-context Oracle quota)
//   - Network is flaky between the demo machine and apigcp.trynia.ai
//   - You just want sub-50ms latency for a known query
//
// The snapshots.json file is regenerated by scripts/capture-snapshots.mjs;
// every entry is a real Nia response, never synthetic.
interface PackSnapshot {
  match: string;
  query: string;
  response: {
    content?: string;
    sources?: Array<string | { url: string }>;
    chunks?: unknown;
    results?: unknown;
  };
}
const snapshots = snapshotsRaw as Record<string, PackSnapshot[]>;

function lookupSnapshot(pack_id: string, query: string): PackSnapshot | null {
  const entries = snapshots[pack_id];
  if (!entries?.length) return null;
  const q = query.toLowerCase();
  // Score = matched_tokens / total_match_tokens (precision). A 1-token match
  // that fully hits beats a 2-token match that only half hits.
  let best: { entry: PackSnapshot; score: number; hits: number } | null = null;
  for (const e of entries) {
    const tokens = e.match.toLowerCase().split(/\s+/).filter(Boolean);
    if (tokens.length === 0) continue;
    const hits = tokens.filter((t) => q.includes(t)).length;
    if (hits === 0) continue;
    const score = hits / tokens.length;
    if (!best || score > best.score || (score === best.score && hits > best.hits)) {
      best = { entry: e, score, hits };
    }
  }
  return best?.entry ?? null;
}

// Nia API client — talks to the real /v2 surface at https://apigcp.trynia.ai/v2.
// Auth: Authorization: Bearer <NIA_API_KEY>.
// When NIA_API_KEY is missing we fall back to deterministic fixtures so the
// marketplace + demo flow always work offline.
//
// Nia's MCP server is a *local install* (`npx nia-wizard@latest`), so NiaHub's
// hosted MCP gateway is the value-add: we forward MCP traffic to these REST
// endpoints with the right scope per subscription.

export type NiaSource =
  | { type: 'docs'; url: string; refresh_strategy?: string }
  | { type: 'github'; url: string; branch?: string; paths?: string[] }
  | { type: 'github_issues'; url: string; label_filters?: string[] }
  | { type: 'changelog'; url: string }
  | { type: 'blog'; url: string; tags?: string[] }
  | { type: 'qna'; url: string };

export interface NiaIndex {
  index_id: string;
  status: 'pending' | 'indexing' | 'ready' | 'failed';
  doc_count: number;
  last_indexed_at: string | null;
}

export interface NiaSearchResult {
  chunks: Array<{
    chunk_id: string;
    text: string;
    citation: { url: string; title?: string };
    score: number;
  }>;
  latency_ms: number;
}

async function niaFetch<T>(path: string, init?: RequestInit & { method?: string }): Promise<T> {
  if (!env.nia.apiKey) throw new Error('NIA_API_KEY not configured');
  const res = await fetch(`${env.nia.apiBase}${path}`, {
    ...init,
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${env.nia.apiKey}`,
      ...(init?.headers ?? {}),
    },
    cache: 'no-store',
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Nia ${init?.method ?? 'GET'} ${path} failed: ${res.status} ${body}`);
  }
  return res.json() as Promise<T>;
}

// ---- Source mapping --------------------------------------------------------
// Nia's POST /v2/sources accepts a discriminated SourceCreateRequest with
// type ∈ {"repository","documentation","research_paper",…}. Our pack manifests
// use a friendlier shape — translate here.

interface NiaSourceCreate {
  type: 'repository' | 'documentation' | 'research_paper';
  repository?: string;
  branch?: string;
  ref?: string;
  url?: string;
  url_patterns?: string[];
  display_name?: string;
  focus_instructions?: string;
  crawl_entire_domain?: boolean;
  check_llms_txt?: boolean;
  category_id?: string;
}

function ourSourceToNia(s: NiaSource): NiaSourceCreate {
  switch (s.type) {
    case 'github': {
      const m = /github\.com\/([^/]+\/[^/]+)/.exec(s.url);
      return {
        type: 'repository',
        repository: m ? m[1] : s.url,
        branch: s.branch,
      };
    }
    case 'github_issues': {
      const m = /github\.com\/([^/]+\/[^/]+)/.exec(s.url);
      return {
        type: 'repository',
        repository: m ? m[1] : s.url,
        focus_instructions: s.label_filters?.length
          ? `Index issues with labels: ${s.label_filters.join(', ')}`
          : undefined,
      };
    }
    case 'docs':
    case 'changelog':
    case 'blog':
    case 'qna':
      return {
        type: 'documentation',
        url: s.url,
        crawl_entire_domain: s.type === 'docs',
        check_llms_txt: true,
      };
  }
}

interface NiaSourceResp { id: string; status?: string }

// Nia organizes sources individually; a NiaHub "pack" is a set of sources
// grouped by category. We create a category per pack and attach each source.
export async function createIndex(opts: {
  pack_id: string;
  sources: NiaSource[];
}): Promise<NiaIndex> {
  if (inDemoMode) {
    return {
      index_id: `nia_idx_${opts.pack_id}_${Date.now().toString(36)}`,
      status: 'ready',
      doc_count: 1247,
      last_indexed_at: new Date().toISOString(),
    };
  }
  const cat = await niaFetch<{ id: string }>('/categories', {
    method: 'POST',
    body: JSON.stringify({ name: opts.pack_id, slug: opts.pack_id }),
  });
  const ids: string[] = [];
  for (const s of opts.sources) {
    const created = await niaFetch<NiaSourceResp>('/sources', {
      method: 'POST',
      body: JSON.stringify({ ...ourSourceToNia(s), category_id: cat.id, display_name: opts.pack_id }),
    });
    ids.push(created.id);
  }
  // We use the category id as our pack-scoped index handle. Search calls below
  // pass it as the `category` filter on /search/unified.
  return {
    index_id: cat.id,
    status: 'indexing',
    doc_count: 0,
    last_indexed_at: null,
  };
}

export async function getIndex(indexId: string): Promise<NiaIndex> {
  if (inDemoMode) {
    return {
      index_id: indexId,
      status: 'ready',
      doc_count: 1247,
      last_indexed_at: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
    };
  }
  // List sources scoped to this category, derive aggregate status.
  const list = await niaFetch<{ sources: Array<{ id: string; status?: string; updated_at?: string }> }>(
    `/sources?category_id=${encodeURIComponent(indexId)}`,
  );
  const all = list.sources ?? [];
  const allReady = all.length > 0 && all.every((s) => (s.status ?? 'ready') === 'ready');
  const anyFailed = all.some((s) => s.status === 'failed');
  const last = all
    .map((s) => s.updated_at ?? '')
    .sort()
    .pop();
  return {
    index_id: indexId,
    status: anyFailed ? 'failed' : allReady ? 'ready' : 'indexing',
    doc_count: all.length,
    last_indexed_at: last || null,
  };
}

// ---- Search ----------------------------------------------------------------

interface UnifiedSearchResp {
  results?: Array<{
    id?: string;
    content?: string;
    text?: string;
    snippet?: string;
    score?: number;
    source?: { url?: string; title?: string };
    url?: string;
    title?: string;
  }>;
  chunks?: UnifiedSearchResp['results'];
}

// Build Nia query-mode filters from a pack's sources manifest.
// docs/blog/changelog/qna sources → data_sources (URL identifiers)
// github / github_issues             → repositories ("owner/repo")
function buildPackFilters(sources: NiaSource[]): {
  data_sources: string[];
  repositories: string[];
} {
  const data_sources: string[] = [];
  const repositories: string[] = [];
  for (const s of sources) {
    if (s.type === 'github' || s.type === 'github_issues') {
      const m = /github\.com\/([^/]+\/[^/]+)/.exec(s.url);
      if (m) repositories.push(m[1]!.replace(/\.git$/, ''));
    } else {
      data_sources.push(s.url);
    }
  }
  return { data_sources, repositories };
}

export async function search(opts: {
  index_id: string;          // Nia category id — used as the per-pack scope.
  query: string;
  user_id: string;
  sources: NiaSource[];      // pack manifest, used to build filters
  k?: number;
  pack_id?: string;          // optional — used to look up snapshots
}): Promise<NiaSearchResult> {
  const start = Date.now();

  // Snapshot-first: if the query matches a pre-captured demo response,
  // return it instantly. Skips both demo-mode and the live API.
  if (opts.pack_id) {
    const snap = lookupSnapshot(opts.pack_id, opts.query);
    if (snap) return snapshotToResult(snap, opts.k ?? 5, Date.now() - start);
  }

  if (inDemoMode) return demoSearch(opts.index_id, opts.query, opts.k ?? 5);
  const { data_sources, repositories } = buildPackFilters(opts.sources);

  // Use query mode + data_sources/repositories filters so we scope to *this
  // pack*. Universal mode searches the user's whole Nia account — that bleeds
  // unrelated indexes (razorpay, withorb…) into per-pack results.
  let r: {
    content?: string;
    sources?: unknown;
    chunks?: unknown;
    results?: unknown;
    follow_up_questions?: unknown;
  };
  try {
    r = await niaFetch('/search', {
      method: 'POST',
      body: JSON.stringify({
        mode: 'query',
        messages: [{ role: 'user', content: opts.query }],
        ...(data_sources.length ? { data_sources } : {}),
        ...(repositories.length ? { repositories } : {}),
        include_sources: true,
        fast_mode: true,
        search_mode: 'hybrid',
      }),
    });
  } catch (err) {
    const msg = (err as Error).message;
    if (msg.includes('404') || msg.includes('400')) {
      const demo = demoSearch(opts.index_id, opts.query, opts.k ?? 5);
      demo.chunks.unshift({
        chunk_id: 'placeholder',
        text:
          `(No indexed sources matched yet. If you just bootstrapped the pack, ` +
          `Nia is still indexing — try again in a minute.)`,
        citation: { url: 'https://docs.trynia.ai' },
        score: 0,
      });
      return demo;
    }
    throw err;
  }

  // Query mode returns { content: <synthesized answer>, sources: [<urls>] }.
  // We surface the answer as the lead chunk and the source URLs as separate
  // citation chunks so the MCP host renders a list it can hyperlink.
  const k = opts.k ?? 5;
  const content = typeof r.content === 'string' ? r.content : '';
  const urlList: string[] = Array.isArray(r.sources)
    ? (r.sources as unknown[]).map((s) =>
        typeof s === 'string'
          ? s
          : (s as { url?: string }).url ?? '',
      ).filter(Boolean)
    : [];

  // De-dup and cap.
  const dedupedUrls = Array.from(new Set(urlList)).slice(0, k);

  const chunks: NiaSearchResult['chunks'] = [];
  if (content) {
    chunks.push({
      chunk_id: 'answer',
      text: content,
      citation: { url: dedupedUrls[0] ?? '', title: 'Synthesized from pack sources' },
      score: 1,
    });
  }
  dedupedUrls.forEach((url, i) =>
    chunks.push({
      chunk_id: `src${i}`,
      text: `Cited source: ${url}`,
      citation: { url },
      score: 0.9 - i * 0.05,
    }),
  );

  // Fall back to chunk-style results if the response surprised us.
  if (chunks.length === 0) {
    const raw =
      (r.chunks as unknown[] | undefined) ??
      (r.results as unknown[] | undefined) ??
      [];
    return {
      chunks: (raw as Array<Record<string, unknown>>).slice(0, k).map((c, i) => ({
        chunk_id: String(c.id ?? `c${i}`),
        text: String(c.content ?? c.text ?? c.snippet ?? ''),
        citation: {
          url: String((c.source as { url?: string } | undefined)?.url ?? c.url ?? ''),
          title: (c.source as { title?: string } | undefined)?.title ?? (c.title as string | undefined),
        },
        score: typeof c.score === 'number' ? c.score : 0,
      })),
      latency_ms: Date.now() - start,
    };
  }
  return { chunks, latency_ms: Date.now() - start };
}

// ---- MCP routing -----------------------------------------------------------
// Nia's MCP server is local-install. NiaHub is the *hosted* MCP gateway, so
// this URL points back at our own /api/mcp/<pack_id> route — which is what
// the niahub-mcp npm forwarder posts to.
export function mcpUrlFor(packId: string, token: string): string {
  return `${env.app.url}/api/mcp/${encodeURIComponent(packId)}?token=${encodeURIComponent(token)}`;
}

// ---- Cross-session memory --------------------------------------------------
// Backed by Nia /v2/context-sharing.

export async function saveContext(opts: {
  user_id: string;
  key: string;
  value: unknown;
}): Promise<{ ok: true }> {
  if (inDemoMode) return { ok: true };
  // Nia /v2/contexts requires title + summary (10-1000) + content (50+) +
  // agent_source. We pad short payloads to satisfy the schema.
  const serialized = JSON.stringify(opts.value);
  const content = serialized.length >= 50 ? serialized : `${serialized}\n${'.'.repeat(50 - serialized.length)}`;
  await niaFetch('/contexts', {
    method: 'POST',
    body: JSON.stringify({
      title: `niahub:${opts.user_id}:${opts.key}`.slice(0, 200),
      summary: `NiaHub cross-session memory entry for key "${opts.key}".`,
      content,
      tags: ['niahub', `user:${opts.user_id}`, `key:${opts.key}`],
      agent_source: 'niahub',
      memory_type: 'fact',
    }),
  });
  return { ok: true };
}

export async function retrieveContext(opts: {
  user_id: string;
  key: string;
}): Promise<{ value: unknown | null }> {
  if (inDemoMode) return { value: null };
  const params = new URLSearchParams({
    q: `niahub:${opts.user_id}:${opts.key}`,
    fields: 'title,content',
  });
  const r = await niaFetch<{ items?: Array<{ content?: string }> }>(
    `/contexts/search?${params}`,
  );
  const hit = (r.items ?? [])[0];
  if (!hit?.content) return { value: null };
  try { return { value: JSON.parse(hit.content) }; } catch { return { value: hit.content }; }
}

// ---- Oracle ----------------------------------------------------------------
// /v2/oracle/jobs is asynchronous. We dispatch and poll for up to ~30s; if
// Oracle is slow we fall back to the demo ranker rather than block the UI.

export interface OracleRecommendation {
  pack_id: string;
  rationale: string;
  confidence: number;
}

interface OracleJobCreated { job_id: string }
interface OracleJobStatus {
  status: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';
  result?: { recommendations?: OracleRecommendation[]; answer?: string };
}

export async function oracleRecommend(opts: {
  user_intent: string;
  candidate_pack_ids: string[];
  k?: number;
}): Promise<OracleRecommendation[]> {
  if (inDemoMode) return demoOracle(opts);

  let created: OracleJobCreated;
  try {
    created = await niaFetch<OracleJobCreated>('/oracle/jobs', {
      method: 'POST',
      body: JSON.stringify({
        query:
          `Given a developer's stated intent and a list of NiaHub pack ids, ` +
          `pick the ${opts.k ?? 3} best packs and explain why in one sentence each. ` +
          `Return a JSON array of {pack_id, rationale, confidence (0..1)}.\n\n` +
          `Intent: ${opts.user_intent}\nCandidate pack_ids: ${opts.candidate_pack_ids.join(', ')}`,
        output_format: 'json',
      }),
    });
  } catch (err) {
    // Oracle has a daily 1M-context quota. When we hit it (429) we can't make
    // the user's request fail — fall back to the deterministic ranker so the
    // marketplace keeps recommending. Same fallback on any server-side error.
    const msg = (err as Error).message;
    if (/\b(429|500|502|503|504)\b/.test(msg)) return demoOracle(opts);
    throw err;
  }

  const deadline = Date.now() + 30_000;
  while (Date.now() < deadline) {
    const status = await niaFetch<OracleJobStatus>(`/oracle/jobs/${encodeURIComponent(created.job_id)}`);
    if (status.status === 'completed') {
      const recs = status.result?.recommendations;
      if (Array.isArray(recs) && recs.length) return recs.slice(0, opts.k ?? 3);
      const parsed = tryParseRecs(status.result?.answer ?? '');
      if (parsed.length) return parsed.slice(0, opts.k ?? 3);
      break;
    }
    if (status.status === 'failed' || status.status === 'cancelled') break;
    await new Promise((r) => setTimeout(r, 1000));
  }
  return demoOracle(opts);
}

function tryParseRecs(text: string): OracleRecommendation[] {
  const m = text.match(/\[[\s\S]*\]/);
  if (!m) return [];
  try {
    const arr = JSON.parse(m[0]) as OracleRecommendation[];
    return arr.filter((r) => r && typeof r.pack_id === 'string');
  } catch { return []; }
}

function snapshotToResult(snap: PackSnapshot, k: number, latency_ms: number): NiaSearchResult {
  const r = snap.response;
  const content = typeof r.content === 'string' ? r.content : '';
  const urls: string[] = Array.isArray(r.sources)
    ? r.sources.map((s) => (typeof s === 'string' ? s : s.url)).filter(Boolean)
    : [];
  const dedupedUrls = Array.from(new Set(urls)).slice(0, k);
  const chunks: NiaSearchResult['chunks'] = [];
  if (content) {
    chunks.push({
      chunk_id: 'answer',
      text: content,
      citation: { url: dedupedUrls[0] ?? '', title: 'Synthesized from pack sources' },
      score: 1,
    });
  }
  dedupedUrls.forEach((url, i) =>
    chunks.push({ chunk_id: `src${i}`, text: `Cited source: ${url}`, citation: { url }, score: 0.9 - i * 0.05 }),
  );
  return { chunks, latency_ms };
}

// ---- demo fixtures (only when NIA_API_KEY is missing) ----------------------

function demoSearch(indexId: string, query: string, k: number): NiaSearchResult {
  const seed: Record<string, NiaSearchResult['chunks']> = {
    nia_idx_stripe_001: [
      {
        chunk_id: 'c1',
        text: 'Use Checkout Sessions in subscription mode and pass subscription_data.trial_period_days to start a trial.',
        citation: { url: 'https://docs.stripe.com/payments/checkout/free-trials', title: 'Free trials with Checkout' },
        score: 0.93,
      },
      {
        chunk_id: 'c2',
        text: "stripe.checkout.sessions.create({ mode: 'subscription', line_items: [...], subscription_data: { trial_period_days: 14 } })",
        citation: { url: 'https://github.com/stripe/stripe-node/blob/master/types/Checkout/SessionsResource.d.ts', title: 'stripe-node SessionsResource' },
        score: 0.91,
      },
    ],
  };
  const chunks =
    seed[indexId] ?? [
      {
        chunk_id: 'c1',
        text: `(${indexId}) Top match for "${query}" — current canonical doc.`,
        citation: { url: 'https://example.com', title: 'Canonical source' },
        score: 0.88,
      },
    ];
  return { chunks: chunks.slice(0, k), latency_ms: 132 };
}

function demoOracle(opts: { user_intent: string; candidate_pack_ids: string[] }): OracleRecommendation[] {
  const intent = opts.user_intent.toLowerCase();
  const score = (id: string): number => {
    let s = 0;
    if (intent.includes('next') && id.includes('next')) s += 3;
    if (intent.includes('stripe') && id.includes('stripe')) s += 3;
    if (intent.includes('postgres') && id.includes('postgres')) s += 3;
    if (intent.includes('react') && id.includes('react')) s += 2;
    if (intent.includes('s3') && id.includes('s3')) s += 2;
    if (intent.includes('tailwind') && id.includes('tailwind')) s += 2;
    if (intent.includes('mcp') && id.includes('mcp')) s += 2;
    return s;
  };
  return opts.candidate_pack_ids
    .map((id) => ({
      pack_id: id,
      rationale: `Mentioned in intent: matches "${id.split('-')[0]}" topic with high confidence.`,
      confidence: Math.min(0.99, 0.55 + score(id) * 0.1),
    }))
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 3);
}
